-- Migration 007: Calendar integration
-- Adds tables for calendar sync and cross-domain correlation

-- Calendar events cache
CREATE TABLE IF NOT EXISTS calendar_events (
    id TEXT PRIMARY KEY,
    space_id TEXT NOT NULL,
    external_id TEXT NOT NULL,
    calendar_id TEXT DEFAULT 'primary',
    summary TEXT,
    description TEXT,
    location TEXT,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    all_day BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'confirmed',
    organizer TEXT,
    html_link TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(space_id, external_id)
);

-- Event attendees
CREATE TABLE IF NOT EXISTS calendar_attendees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL,
    email TEXT NOT NULL,
    display_name TEXT,
    response_status TEXT DEFAULT 'needsAction',
    is_organizer BOOLEAN DEFAULT FALSE,
    is_self BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (event_id) REFERENCES calendar_events(id) ON DELETE CASCADE,
    UNIQUE(event_id, email)
);

-- Event reminders
CREATE TABLE IF NOT EXISTS calendar_reminders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL,
    method TEXT NOT NULL,
    minutes INTEGER NOT NULL,
    FOREIGN KEY (event_id) REFERENCES calendar_events(id) ON DELETE CASCADE
);

-- Cross-domain correlations
CREATE TABLE IF NOT EXISTS correlations (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    score REAL NOT NULL,
    reason TEXT,
    matched_terms TEXT, -- JSON array
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES calendar_events(id) ON DELETE CASCADE,
    UNIQUE(item_id, event_id)
);

-- Insights generated by cross-domain engine
CREATE TABLE IF NOT EXISTS insights (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority INTEGER DEFAULT 2,
    source_items TEXT, -- JSON array
    source_events TEXT, -- JSON array
    actions TEXT, -- JSON array
    metadata TEXT, -- JSON object
    status TEXT DEFAULT 'pending', -- pending, viewed, actioned, dismissed
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    viewed_at DATETIME,
    actioned_at DATETIME
);

-- Briefing history
CREATE TABLE IF NOT EXISTS briefings (
    id TEXT PRIMARY KEY,
    date DATE NOT NULL,
    summary TEXT,
    sections TEXT NOT NULL, -- JSON
    stats TEXT, -- JSON
    priorities TEXT, -- JSON
    calendar_items TEXT, -- JSON
    format TEXT DEFAULT 'markdown',
    generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    delivered_at DATETIME,
    delivery_channels TEXT -- JSON array
);

-- Briefing delivery log
CREATE TABLE IF NOT EXISTS briefing_deliveries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    briefing_id TEXT NOT NULL,
    channel TEXT NOT NULL,
    success BOOLEAN NOT NULL,
    message_id TEXT,
    error TEXT,
    delivered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (briefing_id) REFERENCES briefings(id) ON DELETE CASCADE
);

-- Action execution log (for the 3-mode action framework)
CREATE TABLE IF NOT EXISTS action_log (
    id TEXT PRIMARY KEY,
    action_type TEXT NOT NULL,
    item_id TEXT,
    hat_id TEXT,
    description TEXT,
    parameters TEXT, -- JSON
    confidence REAL,
    mode TEXT NOT NULL, -- suggest, supervised, autonomous
    status TEXT NOT NULL,
    result TEXT, -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    executed_at DATETIME,
    undone_at DATETIME
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_calendar_events_space ON calendar_events(space_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_time ON calendar_events(start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_calendar_events_synced ON calendar_events(synced_at);
CREATE INDEX IF NOT EXISTS idx_correlations_item ON correlations(item_id);
CREATE INDEX IF NOT EXISTS idx_correlations_event ON correlations(event_id);
CREATE INDEX IF NOT EXISTS idx_insights_type ON insights(type);
CREATE INDEX IF NOT EXISTS idx_insights_status ON insights(status);
CREATE INDEX IF NOT EXISTS idx_insights_created ON insights(created_at);
CREATE INDEX IF NOT EXISTS idx_briefings_date ON briefings(date);
CREATE INDEX IF NOT EXISTS idx_action_log_item ON action_log(item_id);
CREATE INDEX IF NOT EXISTS idx_action_log_status ON action_log(status);
CREATE INDEX IF NOT EXISTS idx_action_log_created ON action_log(created_at);

-- Add calendar_id to spaces if it doesn't exist
-- This tracks which calendar is linked to each space
-- SQLite doesn't support ALTER TABLE ADD COLUMN IF NOT EXISTS,
-- so we use a workaround by checking if the column exists first

-- Note: Run this only if the column doesn't exist:
-- ALTER TABLE spaces ADD COLUMN calendar_sync_token TEXT;
-- ALTER TABLE spaces ADD COLUMN calendar_last_sync DATETIME;
